spring:
  profiles:
    active: release

rsa:
  # rsa密钥生成数量
  count: 50
  # rsa密钥长度
  length: 512

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql